name: nishant_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.2
  dotted_border: ^3.1.0
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.4.0
  flutter_map: ^8.2.2
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_fonts: ^8.0.2
  http: ^1.6.0
  intl: ^0.20.2
  latlong2: ^0.9.1
  lottie: ^3.3.2
  permission_handler: ^12.0.1
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0
  speech_to_text: ^7.3.0
  zego_uikit_prebuilt_call: ^4.22.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/
    - assets/lottie/

